#!/usr/bin/env python3
"""Merge batched translator-agent annotations into seeds/persian.json.

Reads:
  - seeds/persian.json (base — Persian text, transliterations)
  - /tmp/rubaiyat/annotations_batch_*.json (per-batch enrichments)

For each Persian quatrain, layers in the batch fields:
  literal, poetic, theme, note, fg_1st, fg_5th, whinfield

Writes back to seeds/persian.json (enriched in place). Idempotent.

Run: python3 data/merge_annotations.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
SEED = ROOT / "seeds" / "persian.json"
BATCH_DIR = Path("/tmp/rubaiyat")
ENRICH_KEYS = ("literal", "poetic", "theme", "note",
               "fg_1st", "fg_5th", "whinfield")


def main():
    base = json.loads(SEED.read_text(encoding="utf-8"))
    quatrains = base["quatrains"]
    by_num = {q["num"]: q for q in quatrains}

    merged_count = 0
    batch_files = sorted(BATCH_DIR.glob("annotations_batch_*.json"))
    if not batch_files:
        print(f"No batch files found in {BATCH_DIR}")
        return
    print(f"Found {len(batch_files)} batch file(s):")
    for bf in batch_files:
        batch = json.loads(bf.read_text(encoding="utf-8"))
        in_range = 0
        for entry in batch:
            num = entry.get("num")
            if num not in by_num:
                continue
            q = by_num[num]
            for k in ENRICH_KEYS:
                if k in entry:
                    q[k] = entry[k]
            in_range += 1
            merged_count += 1
        print(f"  {bf.name}: merged {in_range} entries")

    # Update count + enrichment metadata
    base["count"] = len(quatrains)
    meta = base.setdefault("_meta", {})
    enriched = sum(1 for q in quatrains if "literal" in q)
    meta["enrichment"] = {
        "count": enriched,
        "coverage": f"{enriched}/{len(quatrains)}",
        "fields": list(ENRICH_KEYS),
        "modern_translations": "literal + poetic generated by Claude (Anthropic)",
        "historical_matches": "FG 1st/5th (Gutenberg #246) + Whinfield 1883 (Gutenberg #38511), matched by LLM review.",
    }

    SEED.write_text(
        json.dumps(base, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"\nEnriched {enriched}/{len(quatrains)} quatrains in {SEED.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
